# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.combo_X = QtWidgets.QComboBox(self.centralwidget)
        self.combo_X.setGeometry(QtCore.QRect(120, 100, 201, 141))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.combo_X.setFont(font)
        self.combo_X.setObjectName("combo_X")
        self.combo_X.addItem("")
        self.combo_X.addItem("")
        self.combo_Y = QtWidgets.QComboBox(self.centralwidget)
        self.combo_Y.setGeometry(QtCore.QRect(520, 100, 201, 141))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.combo_Y.setFont(font)
        self.combo_Y.setObjectName("combo_Y")
        self.combo_Y.addItem("")
        self.combo_Y.addItem("")
        self.button = QtWidgets.QPushButton(self.centralwidget)
        self.button.setGeometry(QtCore.QRect(330, 340, 171, 81))
        font = QtGui.QFont()
        font.setFamily("Pristina")
        font.setPointSize(28)
        self.button.setFont(font)
        self.button.setObjectName("button")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(146, 440, 471, 71))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.combo_Y.addItem("Fuck")
        self.combo_X.addItem("Love")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.button.clicked.connect(self.pressed)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.combo_X.setItemText(0, _translate("MainWindow", "1"))
        self.combo_X.setItemText(1, _translate("MainWindow", "0"))
        self.combo_Y.setItemText(0, _translate("MainWindow", "1"))
        self.combo_Y.setItemText(1, _translate("MainWindow", "0"))
        self.button.setText(_translate("MainWindow", "Check"))
        self.label.setText(_translate("MainWindow", "Answer :"))
        self.label.adjustSize()
    def pressed(self):

        try:
            x = int((self.combo_X.currentText()))
            y = int((self.combo_Y.currentText()))
            xxx=x+y
            print(xxx)
            self.label.setText(f"Answer : {xxx}  ")
        except:
            my=self.combo_X.currentText()+" "+self.combo_Y.currentText()
            self.label.setText(f"Answer : {my}  ")


        self.label.adjustSize()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
