

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(462, 774)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.outputLabel = QtWidgets.QLabel(self.centralwidget)
        self.outputLabel.setGeometry(QtCore.QRect(10, 20, 441, 101))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.outputLabel.setFont(font)
        self.outputLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.outputLabel.setLineWidth(4)
        self.outputLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.outputLabel.setObjectName("outputLabel")
        self.percentButton = QtWidgets.QPushButton(self.centralwidget,clicked= lambda:self.press_it("%"))
        self.percentButton.setGeometry(QtCore.QRect(20, 140, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.percentButton.setFont(font)
        self.percentButton.setObjectName("percentButton")
        self.cButton = QtWidgets.QPushButton(self.centralwidget,clicked= lambda:self.press_it("c"))
        self.cButton.setGeometry(QtCore.QRect(80, 140, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.cButton.setFont(font)
        self.cButton.setObjectName("cButton")
        self.arrowButton = QtWidgets.QPushButton(self.centralwidget,clicked= lambda:self.remove_it())
        self.arrowButton.setGeometry(QtCore.QRect(150, 140, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.arrowButton.setFont(font)
        self.arrowButton.setObjectName("arrowButton")
        self.divideButton = QtWidgets.QPushButton(self.centralwidget,clicked= lambda:self.press_it("/"))
        self.divideButton.setGeometry(QtCore.QRect(220, 140, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.divideButton.setFont(font)
        self.divideButton.setObjectName("divideButton")
        self.multiplyButton = QtWidgets.QPushButton(self.centralwidget,clicked= lambda:self.press_it("x"))
        self.multiplyButton.setGeometry(QtCore.QRect(220, 200, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.multiplyButton.setFont(font)
        self.multiplyButton.setObjectName("multiplyButton")
        self.nineButton = QtWidgets.QPushButton(self.centralwidget,clicked= lambda:self.press_it("9"))
        self.nineButton.setGeometry(QtCore.QRect(150, 200, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.nineButton.setFont(font)
        self.nineButton.setObjectName("nineButton")
        self.eightButton = QtWidgets.QPushButton(self.centralwidget,clicked= lambda:self.press_it("8"))
        self.eightButton.setGeometry(QtCore.QRect(80, 200, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.eightButton.setFont(font)
        self.eightButton.setObjectName("eightButton")
        self.sevenButton = QtWidgets.QPushButton(self.centralwidget,clicked= lambda:self.press_it("7"))
        self.sevenButton.setGeometry(QtCore.QRect(20, 200, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.sevenButton.setFont(font)
        self.sevenButton.setObjectName("sevenButton")
        self.minusButton = QtWidgets.QPushButton(self.centralwidget,clicked= lambda:self.press_it("-"))
        self.minusButton.setGeometry(QtCore.QRect(220, 260, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.minusButton.setFont(font)
        self.minusButton.setObjectName("minusButton")
        self.sixButton = QtWidgets.QPushButton(self.centralwidget,clicked= lambda:self.press_it("6"))
        self.sixButton.setGeometry(QtCore.QRect(150, 260, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.sixButton.setFont(font)
        self.sixButton.setObjectName("sixButton")
        self.fiveButton = QtWidgets.QPushButton(self.centralwidget,clicked= lambda:self.press_it("5"))
        self.fiveButton.setGeometry(QtCore.QRect(80, 260, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.fiveButton.setFont(font)
        self.fiveButton.setObjectName("fiveButton")
        self.fourButton = QtWidgets.QPushButton(self.centralwidget,clicked= lambda:self.press_it("4"))
        self.fourButton.setGeometry(QtCore.QRect(20, 260, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.fourButton.setFont(font)
        self.fourButton.setObjectName("fourButton")
        self.plusButton = QtWidgets.QPushButton(self.centralwidget,clicked= lambda:self.press_it("+"))
        self.plusButton.setGeometry(QtCore.QRect(220, 320, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.plusButton.setFont(font)
        self.plusButton.setObjectName("plusButton")
        self.threeButton = QtWidgets.QPushButton(self.centralwidget,clicked= lambda:self.press_it("3"))
        self.threeButton.setGeometry(QtCore.QRect(150, 320, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.threeButton.setFont(font)
        self.threeButton.setObjectName("threeButton")
        self.twoButton = QtWidgets.QPushButton(self.centralwidget,clicked= lambda:self.press_it("2"))
        self.twoButton.setGeometry(QtCore.QRect(80, 320, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.twoButton.setFont(font)
        self.twoButton.setObjectName("twoButton")
        self.oneButton = QtWidgets.QPushButton(self.centralwidget,clicked= lambda:self.press_it("1"))
        self.oneButton.setGeometry(QtCore.QRect(20, 320, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.oneButton.setFont(font)
        self.oneButton.setObjectName("oneButton")
        self.equalButton = QtWidgets.QPushButton(self.centralwidget,clicked= lambda:self.press_it("="))
        self.equalButton.setGeometry(QtCore.QRect(220, 380, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.equalButton.setFont(font)
        self.equalButton.setObjectName("equalButton")
        self.pointButton = QtWidgets.QPushButton(self.centralwidget,clicked= lambda:self.dot_it())
        self.pointButton.setGeometry(QtCore.QRect(150, 380, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.pointButton.setFont(font)
        self.pointButton.setObjectName("pointButton")
        self.zeroButton = QtWidgets.QPushButton(self.centralwidget,clicked= lambda:self.press_it("0"))
        self.zeroButton.setGeometry(QtCore.QRect(80, 380, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.zeroButton.setFont(font)
        self.zeroButton.setObjectName("zeroButton")
        self.absButton = QtWidgets.QPushButton(self.centralwidget,clicked= lambda:self.abs_it())
        self.absButton.setGeometry(QtCore.QRect(20, 380, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.absButton.setFont(font)
        self.absButton.setObjectName("absButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 462, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    def abs_it(self):
        screen=self.outputLabel.text()
        if screen[0]!="-":
            screen="-"+screen
        else:
            screen="+"+screen
        self.outputLabel.setText(screen)
    def remove_it(self):
        screen=self.outputLabel.text()
        screen=screen[:-1]
        self.outputLabel.setText(screen)
    def dot_it(self):
        screen=self.outputLabel.text()

        if screen[-1] == ".":
            pass
        else:
            self.outputLabel.setText(f"{screen}.")
    def press_it(self,pressed):
        if pressed=="c":
            self.outputLabel.setText("0")
        else:
            if self.outputLabel.text()=='0':
                self.outputLabel.setText("")
            self.outputLabel.setText(f"{self.outputLabel.text()}{pressed}")

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.outputLabel.setText(_translate("MainWindow", "0"))
        self.percentButton.setText(_translate("MainWindow", "%"))
        self.cButton.setText(_translate("MainWindow", "C"))
        self.arrowButton.setText(_translate("MainWindow", "<<"))
        self.divideButton.setText(_translate("MainWindow", "/"))
        self.multiplyButton.setText(_translate("MainWindow", "x"))
        self.nineButton.setText(_translate("MainWindow", "9"))
        self.eightButton.setText(_translate("MainWindow", "8"))
        self.sevenButton.setText(_translate("MainWindow", "7"))
        self.minusButton.setText(_translate("MainWindow", "-"))
        self.sixButton.setText(_translate("MainWindow", "6"))
        self.fiveButton.setText(_translate("MainWindow", "5"))
        self.fourButton.setText(_translate("MainWindow", "4"))
        self.plusButton.setText(_translate("MainWindow", "+"))
        self.threeButton.setText(_translate("MainWindow", "3"))
        self.twoButton.setText(_translate("MainWindow", "2"))
        self.oneButton.setText(_translate("MainWindow", "1"))
        self.equalButton.setText(_translate("MainWindow", "="))
        self.pointButton.setText(_translate("MainWindow", "."))
        self.zeroButton.setText(_translate("MainWindow", "0"))
        self.absButton.setText(_translate("MainWindow", "+/-"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
